#!/bin/bash

if [ "$1" == "1" ]; then
	USER="${PRIVATE_GIT_USER_USERNAME_1}"
	MAIL="${PRIVATE_GIT_USER_MAIL_1}"
elif [ "$1" == "2" ]; then
	USER="${PRIVATE_GIT_USER_USERNAME_2}"
	MAIL="${PRIVATE_GIT_USER_MAIL_2}"
else
	echo "Usage: change-user-git [num]";
	echo -e "  1  ${PRIVATE_GIT_USER_USERNAME_1}\n  2  ${PRIVATE_GIT_USER_USERNAME_2}";
	exit
fi

git config --global user.name ${USER}
git config --global user.email ${MAIL}
if [ "${?}" -eq 1 ]; then
	echo "Changing user to: ${USER} - ${MAIL}";
else
	echo "Fail to config git user"
fi
